management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        health-check-path: /actuator/health
        service-name: gateway
      host: 192.168.5.55
      port: 8500
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  application:
    name: gateway



server:
  port: 8080

